import { Project } from "@/types/types";

export const complitedWorks: Project[] = [
  {
    image: "/assets/work/1.png",
    category: "Fullstack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/2.png",
    category: "Next.js",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "Next.js",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "MERN-Stack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/1.png",
    category: "WordPress",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/2.png",
    category: "MERN-Stack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "Fullstack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "Next.js",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/1.png",
    category: "WordPress",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/2.png",
    category: "Next.js",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "MERN-Stack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "Next.js",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/1.png",
    category: "WordPress",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/2.png",
    category: "MERN-Stack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "Next.js",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "WordPress",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/1.png",
    category: "Fullstack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/2.png",
    category: "Fullstack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "MERN-Stack",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "WordPress",
    name: "Nexa Website",
    description: "Here I have to write the proper description",
    link: "/",
    github: "/",
  },
];
